# Generated by Django 4.0.1 on 2022-02-18 11:45

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Adresse Courriel')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('dob', models.DateField(default='2000-01-01', null=True, verbose_name='Date de naissance')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Pays')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '-'), ('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D'), ('5', 'E'), ('6', 'F')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200, verbose_name='Nom du Joueur')),
                ('dob', models.DateField(null=True, verbose_name='Date de naissance')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Pays')),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, unique=True, verbose_name='Pays')),
                ('match_played', models.IntegerField(blank=True, default=0)),
                ('won', models.IntegerField(blank=True, default=0)),
                ('draw', models.IntegerField(blank=True, default=0)),
                ('lost', models.IntegerField(blank=True, default=0)),
                ('goal_for', models.IntegerField(blank=True, default=0)),
                ('goal_against', models.IntegerField(blank=True, default=0)),
                ('goal_diff', models.IntegerField(blank=True, default=0)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('group_position', models.IntegerField(blank=True, default=0)),
                ('team_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.group')),
            ],
        ),
    ]
