# Generated by Django 4.0.1 on 2022-02-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_group_teams_alter_group_name_alter_team_team_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='TeamGroup',
        ),
    ]
