# Generated by Django 4.0.1 on 2022-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_group_teamgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='champion',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_group',
            field=models.CharField(choices=[('A', '1'), ('B', '2'), ('C', '3'), ('D', '4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='teamgroup',
            name='name',
            field=models.CharField(choices=[('A', '1'), ('B', '2'), ('C', '3'), ('D', '4')], max_length=2, unique=True),
        ),
    ]
