# Generated by Django 4.0.1 on 2022-02-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(default='2000-01-01', null=True, verbose_name='Date de naissance'),
        ),
    ]
