# Generated by Django 4.0.1 on 2022-02-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_team_champion_alter_team_team_group_and_more'),
        ('backend', '0006_alter_player_dob'),
    ]

    operations = [
    ]
