# Generated by Django 4.0.1 on 2022-02-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_merge_20220223_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='champion',
        ),
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
    ]
